# Training Configuration
training:
  batch_size: 16
  learning_rate: 1e-3
  max_epochs: 1000
  checkpoint_interval: 100
  validation_interval: 50
  early_stopping_patience: 50

# Model Configuration
model:
  encoder_embedding_dim: 512
  encoder_n_convolutions: 3
  encoder_kernel_size: 5
  decoder_rnn_dim: 1024
  decoder_max_step: 1000
  attention_rnn_dim: 1024
  attention_dim: 128
  attention_location_n_filters: 32
  attention_location_kernel_size: 31
  n_mel_channels: 80
  n_frames_per_step: 1
  gate_threshold: 0.5
  p_attention_dropout: 0.1
  p_decoder_dropout: 0.1

# Audio Configuration
audio:
  sample_rate: 22050
  n_fft: 1024
  hop_length: 256
  win_length: 1024
  n_mel_channels: 80
  mel_fmin: 0.0
  mel_fmax: 8000.0

# Data Configuration
data:
  text_cleaners: ['english_cleaners']
  max_wav_value: 32768.0
  sampling_rate: 22050
  filter_length: 1024
  hop_length: 256
  win_length: 1024
  mel_fmin: 0.0
  mel_fmax: 8000.0

# Paths
paths:
  data_root: "data"
  checkpoints: "checkpoints"
  logs: "logs"
  output: "output"
